### ISSUE TITLE
Question about task residual tuning

### ISSUE THREAD

**Issue by Pixie8888** [geekyutao/TaskRes#2]
Hi,

I still didn't get why task residual tuning is better than prompt tuning. I think task residual tuning also damaged the decision boundary of original clip since the classifier weight is changed in eqn. 3. Could you explain the difference with prompt tuning?

**Comment by geekyutao** [comment]
Hi, we actully did some experiments on this. Check out the insghts in Section 2.4 Question 2 "Does TaskRes effectively preserve the pre-trained boundary?" in the [supplementary material](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Yu_Task_Residual_for_CVPR_2023_supplemental.pdf).
